[tool.poetry]
name = "itp270python1"
version = "0.1.0"
description = ""
authors = ["pbolaines <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pip = "^22.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
